#124: Create space favorite
luongvietdung/booking-homestays pull request #13
Opened 2019-08-16 03:55 UTC by hoangcnpd01980

https://github.com/luongvietdung/booking-homestays/pull/12

2019-08-16 04:07 UTC, hieuhv07 approved these changes

2019-08-16 04:31 UTC, CH1006 approved these changes

2019-08-16 06:24 UTC, luongvietdung requested changes

2019-08-16 06:24 UTC, luongvietdung commented on spec/controllers/manager/base_controller_spec.rb
> +# frozen_string_literal: true
Sao tạo ra mấy file spec này làm gì. Xoá những file thừa đi

2019-08-16 06:24 UTC, luongvietdung commented on app/models/favorite_space.rb
> +  validates :name, length: { in: 3..50 }
Thêm validate unique

2019-08-16 06:24 UTC, luongvietdung commented on app/views/shared/_flash.html.slim
> +- flash.each do |name, message|
Để file này vào thư mục shared/manager

2019-08-16 06:24 UTC, luongvietdung commented on app/controllers/manager/favorite_spaces_controller.rb
> +        redirect_to manager_favorite_spaces_path
redirect_to manager_favorite_spaces_path, notice: "Create successfully!!!"

2019-08-16 08:26 UTC, luongvietdung requested changes

2019-08-16 08:26 UTC, luongvietdung commented on app/controllers/manager/favorite_spaces_controller.rb
> +        flash[:danger] = "Wrong!!!"
DÒNG NÀY CÓ CẦN NỮA KHÔNG?

2019-08-16 08:26 UTC, luongvietdung commented on app/views/shared/manager/_flashmessages.html.slim
> +        $(function() {
Cho đoạn này lên assets/javascript. Không viết JS trong file slim

2019-08-16 10:27 UTC, luongvietdung commented on app/views/layouts/manager.html.slim
> +              = render "shared/manager/flashmessages"
rename flashmessages -> flash_messages

2019-08-16 10:27 UTC, luongvietdung commented on app/views/manager/favorite_spaces/new.html.slim
> +
Remove it

2019-08-19 01:12 UTC, hoangcnpd01980 commented on app/views/manager/favorite_spaces/new.html.slim
> +
Tại sao lại phải xóa anh?

2019-08-19 01:24 UTC, luongvietdung commented on app/views/manager/favorite_spaces/new.html.slim
> +
Em để dòng trống này làm gì?

2019-08-19 01:36 UTC, luongvietdung requested changes

2019-08-19 01:36 UTC, luongvietdung commented on app/controllers/application_controller.rb
> +  add_flash_types :success, :info, :warning, :danger
Dòng này có ở trên rồi còn thêm làm gì?

2019-08-19 01:36 UTC, luongvietdung commented on app/controllers/manager/favorite_spaces_controller.rb
> +
Remove blank line

2019-08-19 01:36 UTC, luongvietdung commented on config/routes.rb
> +  devise_for :users
Xoá đi.

2019-08-19 03:24 UTC, luongvietdung approved these changes

2019-08-19 03:24 UTC, merged