124: Create locations
luongvietdung/booking-homestays pull request #16
Opened 2019-08-16 07:36 UTC by hieuhv07

http://192.168.100.19:3333/issues/124

2019-08-16 07:41 UTC, CH1006 approved these changes

2019-08-16 07:44 UTC, hoangcnpd01980 approved these changes

2019-08-16 08:18 UTC, hoangcnpd01980 approved these changes

2019-08-16 08:30 UTC, luongvietdung requested changes

2019-08-16 08:30 UTC, luongvietdung commented on Gemfile
> +gem "i18n", "~> 1.6"
Sao cần gem này làm gì?

2019-08-16 08:30 UTC, luongvietdung commented on app/controllers/manager/locations_controller.rb
> +        flash[:danger] = t ".danger"
Nếu dùng i18n thì thống nhất tất cả đều phải dùng
Hiện tại PR của Hoàng đang ko dùng
Mấy đứa thảo luận đi nhé

2019-08-16 08:38 UTC, hieuhv07 commented on Gemfile
> +gem "i18n", "~> 1.6"
dạ, gem toastr là để mình hiển thị flash, còn cái config là để dùng cho settings kiểu integer, i18n là để đa ngôn ngữ anh

2019-08-16 09:18 UTC, hieuhv07 commented on app/controllers/manager/locations_controller.rb
> +        flash[:danger] = t ".danger"
dạ, bọn em thống nhất dùng i18n anh

2019-08-19 04:23 UTC, luongvietdung requested changes

2019-08-19 04:23 UTC, luongvietdung commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join("config", "locales", "**", "*.{rb,yml}")]
Dòng này để làm gì ?

2019-08-19 04:23 UTC, luongvietdung commented on Gemfile
> +gem "config", "~> 2.0"
Em thêm gem này để làm gì thế

2019-08-19 04:26 UTC, hieuhv07 commented on config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join("config", "locales", "**", "*.{rb,yml}")]
để em chia ra nhiều thư mục để viết i18n cho nó dễ quản lý anh, còn nếu không config thì mình chỉ viết được trong file mặc định của hén thôi anh

2019-08-19 04:29 UTC, hieuhv07 commented on Gemfile
> +gem "config", "~> 2.0"
để setting mấy cái kiểu integer anh

2019-08-19 06:19 UTC, luongvietdung commented on Gemfile
> +gem "config", "~> 2.0"
Nhưng trong PR này có thấy em dùng ở chỗ nào đâu?

2019-08-19 06:25 UTC, hieuhv07 commented on Gemfile
> +gem "config", "~> 2.0"
dạ, rứa để em xóa anh

2019-08-19 06:40 UTC, luongvietdung approved these changes

2019-08-19 06:41 UTC, merged