#119: create room
luongvietdung/booking-homestays pull request #21
Opened 2019-08-19 06:29 UTC by BlackPearl96

http://192.168.100.19:3333/issues/119

2019-08-19 06:40 UTC, CH1006 approved these changes

2019-08-19 06:45 UTC, hieuhv07 approved these changes

2019-08-19 06:56 UTC, hieuhv07 approved these changes

2019-08-19 06:57 UTC, hoangcnpd01980 approved these changes

2019-08-19 07:06 UTC, hieuhv07 approved these changes

2019-08-19 10:12 UTC, hoangcnpd01980 approved these changes

2019-08-19 11:00 UTC, luongvietdung requested changes

2019-08-19 11:00 UTC, luongvietdung commented on app/views/shared/_error_messages.html.slim
> +  #error_explanation
Cái này pull của Hoàng có rồi mà
Sao mọi người review cho nhau mà ko thấy trùng lặp ah

2019-08-19 11:04 UTC, BlackPearl96 commented
ready

2019-08-20 03:22 UTC, luongvietdung commented on app/assets/stylesheets/application.css
> + *= require toastr
Thêm dòng này làm gì?

2019-08-20 03:22 UTC, luongvietdung commented on app/helpers/managers_helper.rb
> +    @locations = Location.sort_by_name.map{ |l| [l.name, l.id] }
Cần gì biến @ ở đây?

2019-08-20 03:22 UTC, luongvietdung commented on app/models/application_record.rb
> +  scope :sort_by_name, -> {order :name}
Chạy rubocop chưa?

2019-08-20 03:22 UTC, luongvietdung commented on app/models/application_record.rb
> +  scope :sort_by_name, -> {order :name}
Order theo ASC or DESC?

2019-08-20 03:26 UTC, BlackPearl96 commented on app/assets/stylesheets/application.css
> + *= require toastr
do em @import vào trong application.scss mà em quên xóa bên này ạ !

2019-08-20 07:09 UTC, luongvietdung requested changes

2019-08-20 07:09 UTC, luongvietdung commented on app/assets/javascripts/manager/custom.js
> +    dropdown[i].addEventListener("click", function() {
$(".dropdown-btn").click(function(e) {
})

2019-08-20 07:09 UTC, luongvietdung commented on app/assets/javascripts/manager/custom.js
> +      this.classList.toggle("active");
$(this).toggleClass('active')

2019-08-20 07:09 UTC, luongvietdung commented on app/assets/javascripts/manager/custom.js
> +      var dropdownContent = this.nextElementSibling;
$(this).next().style('display') ==
$(this).next().style('display', 'hidden')

2019-08-20 07:28 UTC, luongvietdung approved these changes

2019-08-20 07:31 UTC, luongvietdung approved these changes

2019-08-20 07:31 UTC, merged