#137: Edit prices
luongvietdung/booking-homestays pull request #27
Opened 2019-08-20 07:16 UTC by hoangcnpd01980

http://192.168.100.19:3333/issues/137

2019-08-20 07:27 UTC, hieuhv07 approved these changes

2019-08-20 07:35 UTC, BlackPearl96 approved these changes

2019-08-20 08:06 UTC, CH1006 approved these changes

2019-08-21 07:28 UTC, luongvietdung requested changes

2019-08-21 07:28 UTC, luongvietdung commented on app/controllers/manager/prices_controller.rb
> +      if @price.update_attributes(price_params)
Replace `update_attributes` --> `update`

2019-08-21 07:28 UTC, luongvietdung commented on app/views/manager/prices/edit.html.slim
> += form_for [:manager, @price] do |price|
Nên tạo ra partial form sau đó render cho cả edit và new 
tránh dry code

2019-08-21 08:19 UTC, luongvietdung requested changes

2019-08-21 08:19 UTC, luongvietdung commented on app/views/manager/prices/_form.html.slim
> +  = price.submit class: "btn btn-primary"
Không có text của nút ah?

2019-08-21 08:25 UTC, hoangcnpd01980 commented on app/views/manager/prices/_form.html.slim
> +  = price.submit class: "btn btn-primary"
Nếu em dùng price.submit, "Create" thì khi render ra partial cho edit thì nó vẫn dữ nguyên cái text "Create" đó, cho nên em để như thế thì khi vào form new nó sẽ tự động cho mình đoạn text "Create", và khi vào form edit thì nó sẽ tự động cho đoạn text "Update" anh

2019-08-21 08:27 UTC, luongvietdung commented on app/views/manager/prices/_form.html.slim
> +  = price.submit class: "btn btn-primary"
OK

2019-08-21 08:27 UTC, luongvietdung approved these changes

2019-08-21 08:27 UTC, merged