181: create model user
luongvietdung/booking-homestays pull request #8
Opened 2019-08-15 08:30 UTC by CH1006

http://192.168.100.19:3333/issues/181

2019-08-15 08:36 UTC, hoangcnpd01980 approved these changes

2019-08-15 08:43 UTC, BlackPearl96 approved these changes

2019-08-15 08:44 UTC, hoangcnpd01980 approved these changes

2019-08-15 08:47 UTC, hieuhv07 approved these changes

2019-08-15 08:48 UTC, hieuhv07 approved these changes

2019-08-15 08:51 UTC, luongvietdung requested changes

2019-08-15 08:51 UTC, luongvietdung commented on app/models/user.rb
> +  scope :members, -> { where(type: "Member") }
2 Scope này để làm gì?

2019-08-15 09:19 UTC, CH1006 commented on app/models/user.rb
> +  scope :members, -> { where(type: "Member") }
cái này e làm thừa ạ

2019-08-15 09:50 UTC, luongvietdung commented on app/models/user.rb
> +  has_one_attached :avatar
Dòng naỳ để làm gì?

2019-08-15 09:57 UTC, CH1006 commented on app/models/user.rb
> +  has_one_attached :avatar
thêm `avatar` cho `user`, sử dụng `ActiveStorage`, thay vì dùng các gem như `paperclip`, `carrierwave` ạ

2019-08-15 09:58 UTC, luongvietdung commented on app/models/user.rb
> +  has_one_attached :avatar
Anh hiểu nhưng đây là task tạo model mà 
Còn khai báo này dùng cho task đăng ký user mà

2019-08-15 10:06 UTC, CH1006 commented on app/models/user.rb
> +  has_one_attached :avatar
dạ a, để e xóa

2019-08-16 01:03 UTC, luongvietdung approved these changes

2019-08-16 01:03 UTC, merged